server:
  port: 8084
testYmlValue: testReadYmlProperties
testYmlValueAdd: "read Yml Value=:${testYmlValue}"
#spring:
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/testdb
#    username: root
#    password: root
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true